// <auto-generated />
using System;
using EventSupportApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventSupportApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventSupportApp.Data.AuditLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Aksi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Waktu")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLog");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("EventSupportApp.Data.DiskusiPenugasan", b =>
                {
                    b.Property<int>("IdDiskusi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiskusi"));

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<int>("IdPenugasan")
                        .HasColumnType("int");

                    b.Property<int>("IdUserPengirim")
                        .HasColumnType("int");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("WaktuKirim")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDiskusi");

                    b.HasIndex("IdPenugasan");

                    b.HasIndex("IdUserPengirim");

                    b.ToTable("DiskusiPenugasan", (string)null);
                });

            modelBuilder.Entity("EventSupportApp.Data.KebutuhanAcara", b =>
                {
                    b.Property<int>("IdKebutuhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKebutuhan"));

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<bool>("IsAmbil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKembali")
                        .HasColumnType("bit");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdKebutuhan");

                    b.HasIndex("IdAcara");

                    b.ToTable("KebutuhanAcara", (string)null);

                    b.HasData(
                        new
                        {
                            IdKebutuhan = 1,
                            IdAcara = 1,
                            IsAmbil = true,
                            IsKembali = true,
                            Jumlah = 1,
                            Keterangan = "Proyektor utama & Layar gantung",
                            NamaBarang = "Proyektor"
                        },
                        new
                        {
                            IdKebutuhan = 2,
                            IdAcara = 1,
                            IsAmbil = true,
                            IsKembali = true,
                            Jumlah = 1,
                            Keterangan = "Microphone wireless 4 buah & Audio Mixer",
                            NamaBarang = "Sound System"
                        },
                        new
                        {
                            IdKebutuhan = 3,
                            IdAcara = 1,
                            IsAmbil = true,
                            IsKembali = true,
                            Jumlah = 4,
                            Keterangan = "",
                            NamaBarang = "Mic Wireless"
                        },
                        new
                        {
                            IdKebutuhan = 4,
                            IdAcara = 2,
                            IsAmbil = false,
                            IsKembali = false,
                            Jumlah = 1,
                            Keterangan = "Videotron latar panggung utama",
                            NamaBarang = "Proyektor"
                        },
                        new
                        {
                            IdKebutuhan = 5,
                            IdAcara = 2,
                            IsAmbil = false,
                            IsKembali = false,
                            Jumlah = 1,
                            Keterangan = "Sound system outdoor",
                            NamaBarang = "Sound System"
                        },
                        new
                        {
                            IdKebutuhan = 6,
                            IdAcara = 3,
                            IsAmbil = false,
                            IsKembali = false,
                            Jumlah = 1,
                            Keterangan = "Proyektor utama & Layar gantung",
                            NamaBarang = "Proyektor"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.MappingTeknisi", b =>
                {
                    b.Property<int>("IdTeknisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeknisi"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Spesialisasi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatusKetersediaan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTeknisi");

                    b.HasIndex("IdUser");

                    b.ToTable("MappingTeknisi", (string)null);

                    b.HasData(
                        new
                        {
                            IdTeknisi = 1,
                            IdUser = 3,
                            Spesialisasi = "Sound System & Audio",
                            StatusKetersediaan = "Tersedia"
                        },
                        new
                        {
                            IdTeknisi = 2,
                            IdUser = 4,
                            Spesialisasi = "Proyektor & Layar Lebar",
                            StatusKetersediaan = "Tersedia"
                        },
                        new
                        {
                            IdTeknisi = 3,
                            IdUser = 5,
                            Spesialisasi = "Multimedia & Kelistrikan",
                            StatusKetersediaan = "Sibuk"
                        });
                });


            modelBuilder.Entity("EventSupportApp.Data.MasterBarang", b =>
                {
                    b.Property<int>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBarang"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("IdBarang");

                    b.ToTable("MasterBarang");

                    b.HasData(
                        new
                        {
                            IdBarang = 1,
                            Code = "PRY-001",
                            Kategori = "Video",
                            NamaBarang = "Proyektor",
                            Stok = 5
                        },
                        new
                        {
                            IdBarang = 2,
                            Code = "LAY-001",
                            Kategori = "Video",
                            NamaBarang = "Layar Proyektor",
                            Stok = 5
                        },
                        new
                        {
                            IdBarang = 3,
                            Code = "SND-001",
                            Kategori = "Audio",
                            NamaBarang = "Sound System",
                            Stok = 3
                        },
                        new
                        {
                            IdBarang = 4,
                            Code = "MCW-001",
                            Kategori = "Audio",
                            NamaBarang = "Mic Wireless",
                            Stok = 10
                        },
                        new
                        {
                            IdBarang = 5,
                            Code = "MCK-001",
                            Kategori = "Audio",
                            NamaBarang = "Mic Kabel",
                            Stok = 8
                        },
                        new
                        {
                            IdBarang = 6,
                            Code = "LPT-001",
                            Kategori = "Komputer",
                            NamaBarang = "Laptop",
                            Stok = 4
                        },
                        new
                        {
                            IdBarang = 7,
                            Code = "KBR-001",
                            Kategori = "Kelistrikan",
                            NamaBarang = "Kabel Roll",
                            Stok = 6
                        },
                        new
                        {
                            IdBarang = 8,
                            Code = "KBH-001",
                            Kategori = "Kelistrikan",
                            NamaBarang = "Kabel HDMI",
                            Stok = 10
                        },
                        new
                        {
                            IdBarang = 9,
                            Code = "PTR-001",
                            Kategori = "Aksesoris",
                            NamaBarang = "Pointer Presentasi",
                            Stok = 5
                        },
                        new
                        {
                            IdBarang = 10,
                            Code = "WBC-001",
                            Kategori = "Video",
                            NamaBarang = "Webcam",
                            Stok = 3
                        },
                        new
                        {
                            IdBarang = 11,
                            Code = "MXR-001",
                            Kategori = "Audio",
                            NamaBarang = "Mixer Audio",
                            Stok = 2
                        },
                        new
                        {
                            IdBarang = 12,
                            Code = "VDT-001",
                            Kategori = "Video",
                            NamaBarang = "Videotron / LED Wall",
                            Stok = 1
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.MasterLokasi", b =>
                {
                    b.Property<int>("IdLokasi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLokasi"));

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NamaLokasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdLokasi");

                    b.ToTable("MasterLokasi");

                    b.HasData(
                        new
                        {
                            IdLokasi = 1,
                            Keterangan = "Gedung amanah Lantai 1",
                            NamaLokasi = "Gedung amanah Lt. 1"
                        },
                        new
                        {
                            IdLokasi = 2,
                            Keterangan = "Gedung amanah Lantai 2",
                            NamaLokasi = "Gedung amanah Lt. 2"
                        },
                        new
                        {
                            IdLokasi = 3,
                            Keterangan = "Gedung kompeten pintu depan",
                            NamaLokasi = "Gedung kompeten (pintu depan)"
                        },
                        new
                        {
                            IdLokasi = 4,
                            Keterangan = "Gedung kompeten pintu belakang",
                            NamaLokasi = "Gedung kompeten (pintu belakang)"
                        },
                        new
                        {
                            IdLokasi = 5,
                            Keterangan = "Gedung kolaboratif Lantai 1",
                            NamaLokasi = "Gedung kolaboratif Lt.1"
                        },
                        new
                        {
                            IdLokasi = 6,
                            Keterangan = "Gedung kolaboratif Lantai 2",
                            NamaLokasi = "Gedung kolaboratif Lt.2"
                        });
                });


            modelBuilder.Entity("EventSupportApp.Data.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NamaAcara")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdUser");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.Property<int>("IdPenugasan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPenugasan"));

                    b.Property<string>("CatatanTeknisi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DokumentasiKegiatanFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<int>("IdPenugasTeknisi")
                        .HasColumnType("int");

                    b.Property<int>("IdTeknisi")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("StatusPenugasan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("WaktuKonfirmasi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaktuUpload")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPenugasan");

                    b.HasIndex("IdAcara");

                    b.HasIndex("IdPenugasTeknisi");

                    b.HasIndex("IdTeknisi");

                    b.ToTable("Penugasan", (string)null);

                    b.HasData(
                        new
                        {
                            IdPenugasan = 1,
                            DokumentasiKegiatanFile = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=300&h=300&fit=crop",
                            IdAcara = 1,
                            IdPenugasTeknisi = 1,
                            IdTeknisi = 1,
                            Progress = 100,
                            StatusPenugasan = "Selesai"
                        },
                        new
                        {
                            IdPenugasan = 2,
                            IdAcara = 2,
                            IdPenugasTeknisi = 1,
                            IdTeknisi = 1,
                            Progress = 0,
                            StatusPenugasan = "Ditugaskan"
                        },
                        new
                        {
                            IdPenugasan = 3,
                            IdAcara = 3,
                            IdPenugasTeknisi = 1,
                            IdTeknisi = 2,
                            Progress = 0,
                            StatusPenugasan = "Ditugaskan"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NamaRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            NamaRole = "Admin"
                        },
                        new
                        {
                            IdRole = 2,
                            NamaRole = "Helpdesk"
                        },
                        new
                        {
                            IdRole = 3,
                            NamaRole = "Teknisi"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.Property<int>("IdAcara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcara"));

                    b.Property<int>("IdPembuatAcara")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("JamMulai")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("JamSelesai")
                        .HasColumnType("time");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NamaAcara")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusAcara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAcara");

                    b.HasIndex("IdPembuatAcara");

                    b.ToTable("SupportAcara", (string)null);

                    b.HasData(
                        new
                        {
                            IdAcara = 1,
                            IdPembuatAcara = 2,
                            JamMulai = new TimeSpan(0, 8, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 12, 0, 0, 0),
                            Lokasi = "Gedung Rektorat Lt. 1",
                            NamaAcara = "Rapat Pleno Dekanat",
                            StatusAcara = "Selesai",
                            Tanggal = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAcara = 2,
                            IdPembuatAcara = 2,
                            JamMulai = new TimeSpan(0, 8, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 12, 0, 0, 0),
                            Lokasi = "Auditorium BJ Habibie",
                            NamaAcara = "Seminar Nasional IT & AI",
                            StatusAcara = "Ditugaskan",
                            Tanggal = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAcara = 3,
                            IdPembuatAcara = 2,
                            JamMulai = new TimeSpan(0, 9, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 12, 0, 0, 0),
                            Lokasi = "Aula Utama Gedung Rektorat Lt. 3",
                            NamaAcara = "Rapat Pleno Senat Universitas",
                            StatusAcara = "Ditugaskan",
                            Tanggal = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            IdRole = 1,
                            Password = "123",
                            StatusAktif = true,
                            Username = "admin"
                        },
                        new
                        {
                            IdUser = 2,
                            IdRole = 2,
                            Password = "123",
                            StatusAktif = true,
                            Username = "helpdesk"
                        },
                        new
                        {
                            IdUser = 3,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_joko"
                        },
                        new
                        {
                            IdUser = 4,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_budi"
                        },
                        new
                        {
                            IdUser = 5,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_bambang"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.DiskusiPenugasan", b =>
                {
                    b.HasOne("EventSupportApp.Data.Penugasan", "Penugasan")
                        .WithMany("DiskusiList")
                        .HasForeignKey("IdPenugasan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.User", "Pengirim")
                        .WithMany()
                        .HasForeignKey("IdUserPengirim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengirim");

                    b.Navigation("Penugasan");
                });

            modelBuilder.Entity("EventSupportApp.Data.KebutuhanAcara", b =>
                {
                    b.HasOne("EventSupportApp.Data.SupportAcara", "Acara")
                        .WithMany("Kebutuhan")
                        .HasForeignKey("IdAcara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acara");
                });

            modelBuilder.Entity("EventSupportApp.Data.MappingTeknisi", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventSupportApp.Data.Notification", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.HasOne("EventSupportApp.Data.SupportAcara", "Acara")
                        .WithMany("PenugasanList")
                        .HasForeignKey("IdAcara")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.User", "PenugasTeknisi")
                        .WithMany()
                        .HasForeignKey("IdPenugasTeknisi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.MappingTeknisi", "Teknisi")
                        .WithMany()
                        .HasForeignKey("IdTeknisi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acara");

                    b.Navigation("PenugasTeknisi");

                    b.Navigation("Teknisi");
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "PembuatAcara")
                        .WithMany()
                        .HasForeignKey("IdPembuatAcara")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PembuatAcara");
                });

            modelBuilder.Entity("EventSupportApp.Data.User", b =>
                {
                    b.HasOne("EventSupportApp.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.Navigation("DiskusiList");
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.Navigation("Kebutuhan");

                    b.Navigation("PenugasanList");
                });
#pragma warning restore 612, 618
        }
    }
}
