// <auto-generated />
using System;
using EventSupportApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventSupportApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventSupportApp.Data.DiskusiPenugasan", b =>
                {
                    b.Property<int>("IdDiskusi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiskusi"));

                    b.Property<int>("IdPenugasan")
                        .HasColumnType("int");

                    b.Property<int>("IdUserPengirim")
                        .HasColumnType("int");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("WaktuKirim")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDiskusi");

                    b.HasIndex("IdPenugasan");

                    b.HasIndex("IdUserPengirim");

                    b.ToTable("DiskusiPenugasan");
                });

            modelBuilder.Entity("EventSupportApp.Data.KebutuhanAcara", b =>
                {
                    b.Property<int>("IdKebutuhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKebutuhan"));

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<bool>("IsKembali")
                        .HasColumnType("bit");

                    b.Property<string>("JenisKebutuhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdKebutuhan");

                    b.HasIndex("IdAcara");

                    b.ToTable("KebutuhanAcara");

                    b.HasData(
                        new
                        {
                            IdKebutuhan = 1,
                            IdAcara = 1,
                            IsKembali = false,
                            JenisKebutuhan = "Sound System",
                            Jumlah = 1,
                            Keterangan = "Microphone wireless 4 buah & Audio Mixer"
                        },
                        new
                        {
                            IdKebutuhan = 2,
                            IdAcara = 1,
                            IsKembali = false,
                            JenisKebutuhan = "Proyektor",
                            Jumlah = 1,
                            Keterangan = "Proyektor utama & Layar gantung"
                        },
                        new
                        {
                            IdKebutuhan = 3,
                            IdAcara = 2,
                            IsKembali = false,
                            JenisKebutuhan = "Layar LED",
                            Jumlah = 1,
                            Keterangan = "Videotron latar panggung utama"
                        },
                        new
                        {
                            IdKebutuhan = 4,
                            IdAcara = 2,
                            IsKembali = false,
                            JenisKebutuhan = "Sound System",
                            Jumlah = 1,
                            Keterangan = "Sound system konser outdoor / semi-indoor"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.MappingTeknisi", b =>
                {
                    b.Property<int>("IdTeknisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeknisi"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Spesialisasi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatusKetersediaan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTeknisi");

                    b.HasIndex("IdUser");

                    b.ToTable("MappingTeknisi");

                    b.HasData(
                        new
                        {
                            IdTeknisi = 1,
                            IdUser = 3,
                            Spesialisasi = "Sound System & Audio",
                            StatusKetersediaan = "Tersedia"
                        },
                        new
                        {
                            IdTeknisi = 2,
                            IdUser = 4,
                            Spesialisasi = "Proyektor & Layar Lebar",
                            StatusKetersediaan = "Tersedia"
                        },
                        new
                        {
                            IdTeknisi = 3,
                            IdUser = 5,
                            Spesialisasi = "Multimedia & Kelistrikan",
                            StatusKetersediaan = "Sibuk"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdUser");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.Property<int>("IdPenugasan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPenugasan"));

                    b.Property<string>("CatatanTeknisi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DokumentasiKegiatanFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<int>("IdTeknisi")
                        .HasColumnType("int");

                    b.Property<int>("IdUserAdmin")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("StatusPenugasan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupportAcaraIdAcara")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WaktuKonfirmasi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WaktuUpload")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPenugasan");

                    b.HasIndex("IdAcara");

                    b.HasIndex("IdTeknisi");

                    b.HasIndex("IdUserAdmin");

                    b.HasIndex("SupportAcaraIdAcara");

                    b.ToTable("Penugasan");

                    b.HasData(
                        new
                        {
                            IdPenugasan = 1,
                            IdAcara = 1,
                            IdTeknisi = 1,
                            IdUserAdmin = 1,
                            Progress = 0,
                            StatusPenugasan = "Ditugaskan"
                        },
                        new
                        {
                            IdPenugasan = 2,
                            IdAcara = 2,
                            IdTeknisi = 2,
                            IdUserAdmin = 1,
                            Progress = 0,
                            StatusPenugasan = "Ditugaskan"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.RiwayatAcara", b =>
                {
                    b.Property<int>("IdRiwayat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRiwayat"));

                    b.Property<string>("DokumentasiKegiatanFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdAcara")
                        .HasColumnType("int");

                    b.Property<int>("IdPenugasan")
                        .HasColumnType("int");

                    b.Property<string>("NamaAcara")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NamaTeknisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TanggalAcara")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WaktuSelesai")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRiwayat");

                    b.ToTable("RiwayatAcara");
                });

            modelBuilder.Entity("EventSupportApp.Data.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NamaRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            Deskripsi = "Administrator yang menugaskan teknisi dan melihat laporan",
                            NamaRole = "Admin"
                        },
                        new
                        {
                            IdRole = 2,
                            Deskripsi = "Staff yang memasukkan data acara dan kebutuhan support",
                            NamaRole = "Helpdesk"
                        },
                        new
                        {
                            IdRole = 3,
                            Deskripsi = "Staff teknis lapangan yang bertugas mensupport acara",
                            NamaRole = "Teknisi"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.Property<int>("IdAcara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcara"));

                    b.Property<int>("IdUserHelpdesk")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("JamMulai")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("JamSelesai")
                        .HasColumnType("time");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NamaAcara")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusAcara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAcara");

                    b.HasIndex("IdUserHelpdesk");

                    b.ToTable("SupportAcara");

                    b.HasData(
                        new
                        {
                            IdAcara = 1,
                            IdUserHelpdesk = 2,
                            JamMulai = new TimeSpan(0, 9, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 12, 0, 0, 0),
                            Lokasi = "Aula Utama Gedung Rektorat Lt. 3",
                            NamaAcara = "Rapat Pleno Senat Universitas",
                            StatusAcara = "Ditugaskan",
                            Tanggal = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAcara = 2,
                            IdUserHelpdesk = 2,
                            JamMulai = new TimeSpan(0, 13, 0, 0, 0),
                            JamSelesai = new TimeSpan(0, 16, 30, 0, 0),
                            Lokasi = "Auditorium BJ Habibie",
                            NamaAcara = "Seminar Nasional IT & AI",
                            StatusAcara = "Ditugaskan",
                            Tanggal = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            IdRole = 1,
                            Password = "123",
                            StatusAktif = true,
                            Username = "admin"
                        },
                        new
                        {
                            IdUser = 2,
                            IdRole = 2,
                            Password = "123",
                            StatusAktif = true,
                            Username = "helpdesk"
                        },
                        new
                        {
                            IdUser = 3,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_joko"
                        },
                        new
                        {
                            IdUser = 4,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_budi"
                        },
                        new
                        {
                            IdUser = 5,
                            IdRole = 3,
                            Password = "123",
                            StatusAktif = true,
                            Username = "pak_bambang"
                        });
                });

            modelBuilder.Entity("EventSupportApp.Data.DiskusiPenugasan", b =>
                {
                    b.HasOne("EventSupportApp.Data.Penugasan", "Penugasan")
                        .WithMany("DiskusiList")
                        .HasForeignKey("IdPenugasan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.User", "Pengirim")
                        .WithMany()
                        .HasForeignKey("IdUserPengirim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengirim");

                    b.Navigation("Penugasan");
                });

            modelBuilder.Entity("EventSupportApp.Data.KebutuhanAcara", b =>
                {
                    b.HasOne("EventSupportApp.Data.SupportAcara", "Acara")
                        .WithMany("Kebutuhan")
                        .HasForeignKey("IdAcara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acara");
                });

            modelBuilder.Entity("EventSupportApp.Data.MappingTeknisi", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventSupportApp.Data.Notification", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.HasOne("EventSupportApp.Data.SupportAcara", "Acara")
                        .WithMany()
                        .HasForeignKey("IdAcara")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.MappingTeknisi", "Teknisi")
                        .WithMany()
                        .HasForeignKey("IdTeknisi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.User", "Admin")
                        .WithMany()
                        .HasForeignKey("IdUserAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventSupportApp.Data.SupportAcara", null)
                        .WithMany("PenugasanList")
                        .HasForeignKey("SupportAcaraIdAcara");

                    b.Navigation("Acara");

                    b.Navigation("Admin");

                    b.Navigation("Teknisi");
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.HasOne("EventSupportApp.Data.User", "Helpdesk")
                        .WithMany()
                        .HasForeignKey("IdUserHelpdesk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Helpdesk");
                });

            modelBuilder.Entity("EventSupportApp.Data.User", b =>
                {
                    b.HasOne("EventSupportApp.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EventSupportApp.Data.Penugasan", b =>
                {
                    b.Navigation("DiskusiList");
                });

            modelBuilder.Entity("EventSupportApp.Data.SupportAcara", b =>
                {
                    b.Navigation("Kebutuhan");

                    b.Navigation("PenugasanList");
                });
#pragma warning restore 612, 618
        }
    }
}
